# Generated by Django 4.0.4 on 2022-05-15 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tp_visit', '0001_initial'),
        ('trade_point', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='trade_point_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_point.tradepoint'),
        ),
    ]
